### ISSUE TITLE
PLUMED did not produce python3.9 bindings even when specified

### ISSUE THREAD

**Issue by bartoldeman** [ComputeCanada/software-stack#101]
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/44e24525a2b894b363db9764ae83f1eb5ae553c5/easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.3-gofbc-2020.1.403.114.eb#L33
shows that binding should be produced for 3.7-3.9 but 3.9 is not included, because the dependency:
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/44e24525a2b894b363db9764ae83f1eb5ae553c5/easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.3-gofbc-2020.1.403.114.eb#L27
`scipy-stack/2020a` does not support Python 3.9. Nevertheless the build continues and creates 3.8 bindings twice.

The build should instead complain. This is probably a framework issue but will need to investigate where.

**Comment by mboisson** [comment]
Is the quick fix to depend on `scipy-stack/2021a` ?

**Comment by mboisson** [comment]
Actually, the way to "fix" that is that the PLUMED recipe should have a sanity check for python wrappers. It would then fail on python 3.9, presumably.

**Comment by bartoldeman** [comment]
the log says (after the 3.8 binds are finished) it loads the `python/3.9` module but then merrily continues and all the PATHs still contain `python/3.8`. That's silly.

**Comment by bartoldeman** [comment]
yes the PLUMED easyconfig should depend on `scipy-stack/2021a`

**Comment by mboisson** [comment]
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-main/easybuild/easyconfigs/a/autodiff/autodiff-0.6.0-GCCcore-9.3.0.eb#L49

and the sanity_checks should include `"lib/python%(pyshortver)s/site-packages/"`

**Comment by mboisson** [comment]
I guess that is true for any recipe that uses `multi_deps` for Python in most cases. I wonder if that can be done automatically ?

**Comment by ostueker** [comment]
I'm on it for PLUMED-2.7.3.

**Comment by ostueker** [comment]
Pushing fixed PLUMED to dev tonight and will test tomorrow.

**Comment by ofisette** [comment]
This issue with `multi_deps` is easy to miss, it got me once before. A solution would be to modify our `scipy-stack` modules: the `depends_on` for Python would become a `prereq` and be moved up in the module next to the `conflict`. This would make `module` fail when trying to load an incompatible SciPy stack instead of switching the Python version. I realise this would affect the users too, and I think it would be a good thing! It is never right to replace an explicitly loaded Python by a different minor version.

**Comment by mboisson** [comment]
I don't think we can change to `prereq` without breaking stuff, since `prereq` won't load a python module if none is loaded.

**Comment by ofisette** [comment]
Good point, we could instead do:

**Comment by ofisette** [comment]
The best would be to have a `conflict` function that accepts a range in Lmod, but failing that the above suggestion should work.

**Comment by mboisson** [comment]
This is not really a problem for users, since Lmod will explicitly tell them that the modules are being swapped. It is mostly a problem with automation, when using EasyBuild.

**Comment by bartoldeman** [comment]
I'll try that and see how it works on some easyconfigs.

**Comment by mboisson** [comment]
@bartoldeman, I removed that comment, because it does not work. 

```
$ export LMOD_AUTO_SWAP=no
$ module load scipy-stack/2020a

Les modules suivants ont été rechargés avec un changement de version :
  1) python/3.9.6 => python/3.8.10
```

**Comment by ostueker** [comment]
* The issue with PLUMED's python/3.9 bindings not being built was resolved by using `('SciPy-Stack', '2021a')` instead of `2020a`.  -- Commit 597b87d
* Downstream of that, making sure that configs have `depends_on(between('python','3.7<','<3.10'))`, instead of `between('python','3.7','3.9)` resolved similar issues with OpenMM and OpenMM-PLUMED.

I don't mind so much that the python version changes when modules are loaded, as long as it is always accompanied by a message.  It would have saved me quite some time if such a message would have shown up in the easybuild logs.


Conclusion: Problem with PLUMED is solved. If you want to further discuss turning off or improving how module versions are automatically switched, maybe you want to change the title or split it into a separate issue.

**Comment by mboisson** [comment]
Thanks Oliver. Will close this for now.
