### ISSUE TITLE
Add RSNT_GCC_TARGET to arch modules

### ISSUE THREAD

**Issue by ofisette** [ComputeCanada/software-stack#109]
I propose to add an `RSNT_GCC_TARGET` environment variable for use with `gcc -march=`. This variable would be set/changed at the same time `RSNT_ARCH` is, i.e. when first activating the stack and when loading an `arch` module. This would give stack users and developers an easy way to call GCC and patch code for an optimal CPU target.

For example, on clusters with heterogeneous hardware, using `-march=native` on a login node may result in code that does not work on all compute nodes. Using `-march=$RSNT_GCC_TARGET` would allow a user to compile for the most advanced instruction set that is compatible with the cluster’s hardware.

Another example, Python packages in `wheels_builder` are sometimes patched to prevent the use of `-march=native` (e.g. `roboschool` and `pybinding`). `RSNT_GCC_TARGET` would replace ad hoc code, be more reliable and not require maintenance inside `config` files. Parsing the contents of Python’s `sysconfig.get_config_vars('CFLAGS')` would achieve the same thing, but is more difficult in a shell script.

**Comment by ccoulombe** [comment]
On the login node, it is clearer to remove the `-march=native`, and then you automatically get the correct opt flags based on the login node arch (`RSNT_ARCH`).

For the wheels with c extension, it is the same, many build systems relies on sysconfig which provides the flags from the Python used, which is loaded with arch/avx2 for instance.

Some users uses Intel and not GCC.

In my opinion, we do not need to add another variable since we already get the correct flags based on RSNT_ARCH.
In all these cases, we still need to patch/update/edit so this does not avoid the required maintenance unfortunately.

**Comment by mboisson** [comment]
I think @ofisette's point is that if one has to strip `-march=native` and replace it with something architecture specific, one has to know what is that architecture specific thing. We know what that thing is, but not everyone does. It's like setting `CFLAGS` or similar to automatically have a `-march=...` based on what architecture module is loaded or what was detected for `RSNT_ARCH`. 

I think the proposal has value. However, users would not know to use `RSNT_GCC_TARGET`. It is quite a niche use case. It is pretty much only for building python wheels, since everything we compile with EasyBuild is already handled. I would suggest putting it in the `build_wheels.sh` script itself instead.

**Comment by ccoulombe** [comment]
Am I missing something, but why appending a `-march=core-avx2` to an already present `-march=core-avx2` ? 
The illegal instructions arises because we have `-march=core-avx2 --ftree-vectorize ... -march=native` on an avx512 hardware.
I'd rather strip the flag and not replace it. The rightmost `-march=native` has an impact, removing it fixes the issue it generates. 

It looks to me that a rarer case of CMake (for wheels) not listening would be generalized into `build_wheels.sh`. While one can fix these case by patching or hinting CMake with `CMAKE_` env. variables as we already do.

In my opinion, it is easier, quicker and clearer to simply remove the flag since in all cases we still need to patch the culprit.
With the check in `build_wheels.sh` to look for the presence of `-march=native`, this will be even quicker.

Documenting when a wheel needs to be avx2 versus "general" would be great for others that don't know all the bits.

**Comment by ccoulombe** [comment]
`build_wheels.sh` is already a big bowl of spaghetti so I'd rather avoid adding one more noodle to it.

`arch/avx2 CMAKE_CXX_FLAGS='-march=core-avx2'` is more readable then `CMAKE_CXX_FLAGS='-march=$RSNT_GCC_TARGET'` as it is clear that this particular case is avx2 optimized. In fact, a patch file might be better suited in those few cases for CMake.

We decided to build generic wheels, unless the wheels benefit from optimization. So yes, we need tell CMake what arch it can benefit from. And we don't plan on building systematically multiple wheels for multiples architecture as we do with EB.

This really needs to be documented for others, but since only very few people fixes these kind of wheels I'd favor KISS (_Keep it Simple Stupid_). So I think now this is more about documenting it.

**Comment by ofisette** [comment]
Hard-coding the value would work too, but then I think it would have to be `-march=nocona` if we want wheels to be truly generic. And for arch-dependent wheels that do benefit from optimisations, I guess we would need separate config files and a way to chose between them when we build the wheel? I feel like `RSNT_GCC_TARGET` would be simpler.

I agree with @mboisson that it should be restricted to building wheels after all. It is just as easy to document what `-march` flag should be used on a given cluster than it is to tell users they should use `RSNT_GCC_TARGET`.
