### ISSUE TITLE
Define APPTAINER_* environment variables

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#126]
This ticket is to discuss what `APPTAINER_*` environment variables we should set, and to what value. 

From discussions on Slack, possible useful settings might include: 
* `APPTAINER_TMPDIR` (to a non-NFS, non-Lustre location)
* `APPTAINER_BIND` (to include project and scratch, at least, maybe home ?)
* `APPTAINER_CLEANENV` (-e) 
* `APPTAINER_CONTAIN` (-c) 
* `APPTAINER_CONTAINALL` (-C)

We should try to converge for apptainer 1.2.x module which is not yet there.

**Comment by mboisson** [comment]
My thinking so far is: 
* we should set `APPTAINER_BIND` to have workable `/project` and `/scratch`.  The exact value would be cluster-specific, since not all clusters have the same filesystem layouts. We should probably not set `/home/$USER`, as `.bashrc` scripts from the host are unlikely to work in the container.
* we should set `APPTAINER_TMPDIR` to `/localscratch` if it exists, or another value TBD for clusters that don't have such
* we should set `APPTAINER_CLEANENV` to remove the host environment from the container

**Comment by preney** [comment]
I agree with respect to `APPTAINER_BIND`. `/home` is problematic for these reasons (as I see such):

-  Many images just modify stuff in `$HOME` as if they control everything. These modifications include `~/.bashrc` and similar files. Of course these modifications will only work when executed INSIDE the container --and will fail otherwise.
- Many users will configure settings that are set when initially logged in files such as `~/.bashrc`. Typically these are `module load` and other statements that will ONLY work outside a container.

To avoid issues, users should have to manually bind mount /home themselves if that is what they want/need. This avoids issues where an Apptainer container will fail to work correctly if home exists, container programs modifying settings (e.g., in `~/.bashrc`), and any cluster-specific things that user set that will not work inside a container.

---

With respect to `APPTAINER_TMPDIR` I don't see how we can set such to `/localscratch`. Why? Not all clusters have a `/localscratch`. That said, if all clusters would have such a mount location that is neither NFS nor Lustre, then I agree we should set `APPTAINER_TMPDIR` to that.

---

Personally, I would rather set `APPTAINER_CONTAINALL` as a default. Why? Consider:

- Docker images run with the equivalent of `APPTAINER_CONTAINALL` set and users often are running Apptainer containers that were built from Docker images.
- `APPTAINER_CONTAINALL` is closest to running under a virtual machine as it much more isolated from the host than the other settings. So this becomes an excellent environment to be in to successfully run containers designed with foreign configurations.
- A user can `unset APPTAINER_CONTAINALL` if they do not want this setting.
- `APPTAINER_CONTAINALL` contains very little of the host environment. It is essentially running only using the host's kernel.
- `APPTAINER_CLEANENV` does strip out many things from the host shell environment but not all of them. For example, the `PATH`s not accessible inside a container are removed from `PATH`. While this good other things should be removed too.
- If there are environment variables users should use in their containers, e.g., `SLURM_`*, then we can algorithmically do such so even with `APPTAINER_CONTAINALL` those are set inside the container. Essentially for all `SLURM_`* variables set the env vars `APPTAINERENV_SLURM_`* to the same value which will cause the `SLURM_`* env vars to be defined inside the container.

If others don't agree with me concerning `APPTAINER_CONTAINALL`, then at a minimum `APPTAINER_CLEANENV` should be set. Regardless users can `unset` such to do what they would like. I feel that `APPTAINER_CONTAINALL` should be our default --perhaps with `APPTAINERENV_SLURM_`* env vars set (which, again users can unset) as well.

---

Finally, in the past I've had problems bind mounts involving symlinks and have had to use `realpath` on those symlinks to bind mount successfully. This implies that some testing should be done with systems were `/project`, etc. are symlinks and it may be necessary on those systems to both bind mount `/project` and to bind mount `realpath` of such.

**Comment by preney** [comment]
Just in case, I wish to point out that this issue's topic is not merely a hypothetical discussion.

There are no doubt instances where this becomes a real issue. Consider the NCBI software called PGAP (e.g., https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py and for an example ticket see Ticket 0201553 ) which does various bind mounts on its own. The problem is that if any path the user is trying to use uses symbolic links and the realpath involved (i.e., the path without symlinks) is not ALSO bind mounted, then the user will not be able to access the files/directories/etc. being referred to. By bind mounting a user's projects' (note plural projects), scratch (IMHO it is sufficient to only mount that user's scratch), and documenting that their home directory may need to be mounted as well is probably the best thing to do to minimize issues. Moreover, a user can always unset, etc. these environment variables if that is needed/desired.

ASIDE: In general, to ensure success, Apptainer bind mounts should not have symlinks in their paths unless the realpaths involved with any of those symlinks are also bind mounted.

**Comment by preney** [comment]
A co-worker has suggested setting to `APPTAINERENV_SLURM_TMPDIR=$SLURM_TMPDIR` which would define `SLURM_TMPDIR` inside the container environment.

Problems with this include that `SLURM_TMPDIR` is not defined except within an `sbatch` job --which means it would be defined to be the empty string (i.e., not good IMO). If SLURM_TMPDIR was always set then that would be different. (That said, I mention this here so others can see and comment on such.)

Additionally, I note here that users could easily set such themselves before running the container if such is desired inside the container.

**Comment by bartoldeman** [comment]
I would keep the env vars to the absolute minimum required to avoid surprising behaviour (but not sure which) between apptainer installed elsewhere and apptainer on CC.

As for SLURM_TMPDIR, slurm spank plugins set a bind mount to it on all CC clusters with local storage, `/var/tmp` which works inside and outside jobs.

**Comment by mboisson** [comment]
Maybe a good compromise would be to create our own environment variable, says, `RSNT_APPTAINER_CONVENIENCE_MODE=yes`
`RSNT_APPTAINER_CONVENIENCE_MODE=docker`

which then controls if a bunch of "convenient" variables (such as bind mounts and isolation) are defined when loading the `apptainer` module.

**Comment by mboisson** [comment]
Consensus: 
1. we don’t touch -e, -c, -C
2. we define `APPTAINER_BIND` to automatically bind whatever is needed for `project` and `scratch` filesystems (and that whatever depends on the cluster), the whole filesystem since we don’t know what portion of it will be used by the user
3. we defined `APPTAINER_TMPDIR` to `/var/tmp` (if that works everywhere, or similar if it does not)
4. we don't bind `/home`

**Comment by mboisson** [comment]
This is done
