### ISSUE TITLE
Deprecating StdEnv/2016.4 and StdEnv/2018.3

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#132]
StdEnv versions 2016.4 and 2018.3 are used by few users these days, and they can't be updated easily. There are security issues that occur, which we can't fix easily. 

Proposal is to hide and deprecate these modules, i.e. display a warning message telling users to move on to new stack, and eventually block loading these modules. 

This issue is to collect comments onthis.

**Comment by ostueker** [comment]
As I already wrote on Slack, the old StdEnvs contain several packages that cannot be compiled with modern compilers and haven't been updated in years (presumably because the person who wrote the code in the first place has moved on). For some of those packages there are now modern alternatives, but not for others.

There is still value in keeping the old software stacks around so that they old packages can still be used for reproducibility of results.

I suggest a deprecation message that says "use at your own risk".

**Comment by mboisson** [comment]
This is now done, and these are also hidden.
