### ISSUE TITLE
Custom scripts "sq, diskusage_report" not working under gentoo/2020

### ISSUE THREAD

**Issue by alikerr** [ComputeCanada/software-stack#30]
The custom scripts "sq, diskusage_report" do not seem to work under "gentoo/2020" if "StdEnv/2020" is not loaded.
To reproduce the issue on the cluster:
[~]$  which sq
/cvmfs/soft.computecanada.ca/custom/bin/computecanada/sq
[~]$  module load gentoo/2020
[~]$  sq
-bash: sq: command not found
[~]$  module load StdEnv/2020
[~]$  which sq
/cvmfs/soft.computecanada.ca/custom/bin/computecanada/sq
The same applies for any other script under the same location.

**Comment by mboisson** [comment]
Ah, this is expected. "gentoo" is just the gentoo layer, it does not include the Compute Canada configuration. The switch should be done through loading `StdEnv/2020`

**Comment by mboisson** [comment]
You can also manually load `CCconfig`

**Comment by mboisson** [comment]
But I can see how this may be confusing to users if they are told to load  `gentoo/2020` instead of `StdEnv/2020`.... need to think about it.

**Comment by ostueker** [comment]
Just some wild idea:
Could the `gentoo/2020` module check if there is a `StdEnv<2020` is loaded and in that case print a warning?

Or would that always print a warning when switching from - say - `StdEnv/2018.3` to `StdEnv/2020` because `gentoo/2020` is loaded before `StdEnv/2020` can replace `StdEnv/2018.3`?

**Comment by mboisson** [comment]
It's more complicated than that. It is related to this issue : 
https://github.com/ComputeCanada/software-stack/issues/7

Replacing `StdEnv/2018.3` with ` StdEnv/2020` will have those binaries in the path, because it loads `CCEnv`. But those are Compute Canada specific binaries, so we don't necessarily want to always load them.

**Comment by ofisette** [comment]
Could we modify the current `StdEnv/{2016.4,2018.3}` to also load `CCEnv`, and remove the corresponding stuff (such `prepend_path("PATH","/cvmfs/soft.computecanada.ca/custom/bin/computecanada")`) from `nixpkgs/16.09`?

**Comment by mboisson** [comment]
This was not done, because it breaks existing `StdEnv/{2016.4,2018.3}`

**Comment by mboisson** [comment]
Once issue https://github.com/ComputeCanada/software-stack/issues/42 get resolved, this should be resolved.

**Comment by mboisson** [comment]
This will be fixed by fixing #42 next week.
