### ISSUE TITLE
Cleaning up toolchain versions for gentoo stack

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#8]
Currently, we have : 
- intel-2020a
- iomkl-2020.0.402
- iomkl-2020.0.403
- iomkl-2020a
- iompi-2020.0.402
- iompi-2020.0.403
- iompi-2020a
- iccifort-2020.0.166
- GCC-9.2.0
- GCC-9.3.0
- gompi-2020a
- iimpi-2020a
- iimkl-2020.0
- iimkl-2020a
- iccifort-2020.0.166
- iccifort-2020.1.217
- gomkl-2020.0.403
- gomkl-2020.0.403
- gompi-2020.0.403
- gompi-2020a
- GCCcore-9.2.0
- GCCcore-9.3.0

In other words, it is a mess between GCC 9.2, 9.3, and Intel 2020.0 or 2020.1. 

As a starting set of toolchain, based on what version is actually used in the paths for installed software, my suggestion would be : 
GCC => keep 1 digit
Intel compiler => Keep the year only
MPI => keep major+minor
Cuda => Keep major+minor

That would yield : 
- GCCcore-9
- GCC-9
- iccifort-2020
- gmkl-2020
- iimkl-2020
- gompi-2020.40
- iompi-2020.40
- gomkl-2020.40
- iomkl-2020.40

And when cuda 11 is out
- gcccuda-2020.110
- iccifortcuda-2020.110
- gompic-2020.40.110
- iompic-2020.40.110
- gomklc-2020.40.110   
- iomklc-2020.40.110    

I would suggest removing the former toolchains, and reinstall currently installed software with the latter toolchains.

**Comment by mboisson** [comment]
@bartoldeman, @ccoulombe, can you comment ?

**Comment by ccoulombe** [comment]
Agreed, make sense. 
And the gcc toolchains would use 9.3 I suppose.

**Comment by mboisson** [comment]
> And the gcc toolchains would use 9.3 I suppose.
Yes

**Comment by ccoulombe** [comment]
Is there any reason to keep 9.2?

**Comment by bartoldeman** [comment]
No, the 2020.0* and 9.2 can go, it's alpha-stage gentoo toolchain.

**Comment by bartoldeman** [comment]
But I don't think renaming is a good idea, it just creates differences with upstream.
Unless we want to have a completely different set of toolchain versions versus upstream.

It's a double-edged sword.

On the one hand using upstream toolchain versions where possible makes it easier to use their easyconfigs and contribute them back.

On the other hand the upstream numbering scheme may not be the most logical, but is that important? Most users don't see it.

**Comment by mboisson** [comment]
But so, we would have : 
- 2020a
and then what...

- 2020.312 (if we recompile OpenMPI 312 ?)
- 2020a.110 (if we add CUDA ?) 
etc. ?

How will we know what is what ?

**Comment by mboisson** [comment]
Also, we still will not use `foss` or `intel`. Do upstream have standards for `gomklc` and `iomklc`, and are they used ?

**Comment by ccoulombe** [comment]
I am in favor of continuing on the path we already are since we users of EB are "used" to it. Would'nt be awkward to have two different naming scheme to use when you want to build a software?

**Comment by mboisson** [comment]
Plus side of using `2020a` is that it makes it easier to collaborate with upstream. There are two aspects to this : 
1) Upstream -> CC
2) CC -> Upstream

For 1), this can be easily address either with the hooks (presumably), or with `--try-toolchain` as needed. 
For 2), this can be interesting, but it really only matters if `gomklc` and `iomklc` (and `pomklc`) have some adoption upstream. Also, if we actively use the same combination of versions as upstream as our main toolchains, it is also rather trivial if one wants to contribute back a recipe to swap the version number. We could even imagine a git hook that would do the switch as needed before pushing. 


The downsides are
1) We need to choose how we will version diverging sets of subtoolchains ? 
2) Confusion from staff because whatever we choose as an answer to the above, it will be a different schema. 


Having a toolchain version alias would possibly address all of the concerns, on both sides ?

**Comment by mboisson** [comment]
In the meeting on May 8th, Bart explained that the biggest benefit fo CC -> Upstream would be for subtoolchains. While `gomklc` or `iomklc` don't get used upstream, things like `gompi` or `iimkl` do. 

Part of 2020a are combinations of : 
- GCC 9.3.0
- Intel Compiler 2020.1.217
- OpenMPI 4.0.3
- Intel MPI 2019.7.217  (???) 
- Intel MKL 2020.1.217 (???)    (in iimkl-2020a)
- Intel MKL 2020.0.166 (???)   (in gmkl-2020a)
- OpenBLAS 0.3.9
- FFTW 3.3.8
- ScaLAPACK 2.1.0

**Comment by bartoldeman** [comment]
Some thoughts: so far with Nix we have settled into the following scheme, let's call this scheme 1:
* If the toolchain is compiler-only, use the version of that compiler (e.g. GCC,7.3.0)
* Otherwise within a combination of compilers and linear algebra (e.g. GCC 7.3.0, iccifort 2018.3, imkl 2018.3), where the MKL version must match the iccifort version), use the notation 2018.3[.mpiver][.cudaver], where mpiver is e.g. 312 and cudaver 100. We use the 2018.3 notation also for things that don't have Intel components, e.g. gcccuda 2018.3.101. Carrying this forward we'd have gcccuda 2020.1.110 once CUDA 11 is released.

With Maxime's proposal (if I understand it correctly) I guess it would be more following a stricter component-version scheme, let's say, "scheme 2":
* Use compilerver[.linalgver_if_different][.mpiver][.cudaver], so you get toolchains such as gmkl 9.2020, gompi 9.40 gomkl 9.2020.40, iomkl 2020.40

My proposal, scheme 3, is to use "2020a" for non-compiler-only-toolchains if it exactly matches upstream; and if the MPI/CUDA is different use e.g. 2020a.510.120, for use with OpenMPI 5.1.0 and CUDA 12.0. This matches scheme 1 where "2020.1" is replaced with "2020a" and the OpenMPI/CUDA versions are removed if the version is the same as in the upstream set.
If we need an Intel version in the future that is not in a year{a/b} set we can use scheme 1.

**Comment by mboisson** [comment]
What will happen when we install a new compiler, new toolchains, and they don't match current upstream versions *now*, but they may get used in the future ? For example, if we install GCC 10 now, or Intel 2021. They are not used yet, but they might get used by future upstream toolchains.

**Comment by mboisson** [comment]
Also, what would happen for older toolchains ? Would we retrofit them ? 
I see for example, `gompi,2018a` uses `GCC,6.4.0-2.28`  (w/e this 2.28 means ?), `OpenMPI,2.1.2`, and `gompi,2018b` uses `GCC,7.3.0-2.30` and `OpenMPI,3.1.1`. 

How would we label a toolchain made out of `GCC,7.3.0` + `OpenMPI,2.1.2` ?

I think the -2.28/2.30 is binutils, which we don't use in our model. Version 2019b seems not to have this, but 2019a still does. 

Has this version-suffix been dropped completely for the future in upsteam ? Or will we be stuck with that ?

**Comment by bartoldeman** [comment]
If it's not upstream we can just use "Scheme 1". It's easy to distinguish: year.n is custom, year{a,b} matches upstream. Yes upstream dropped the binutils version suffixes completely, and in general I don't want to retrofit 2019 or earlier ones on Gentoo, there is no point since there are newer bugfix releases available for the compilers (e.g. GCC 7.5.0, 8.4.0)

So if for whatever reason we need GCC-7+OpenMPI 2.1.6, we can call it 2018.3.216 to be in-line with previous versions.

For GCC 10, well somebody may ask for it at some point but that doesn't mean we have to immediately base toolchains on it (much like GCC9 on Nix now, there's a gcc 9.1.0 module but no toolchains that use gcc9); once Intel/CUDA support it one can use 2021.1.xx etc.

**Comment by mboisson** [comment]
Ok. Last question, I think. 

So, upstream has `2019[ab]` toolchains for
- `foss` (we don't use much)
- `fosscuda` (we don't use much)
- `gomkl`      (only for 2019a, not 2019b)
- `gcccuda`   (we use) 
- `gompi`      (we use) 
- `gompic`   (we use) 
- `iccifortcuda`   (only for 2019a, not 2019b) 
- `iimpi`        (we don't use much) 
- `iimpic`      (we don't use much)
- `intel`        (we don't use much) 
- `intelcuda`   (only for 2019a, not 2019b, and we don't use much)


What is the proposal for the missing toolchains or subtoolchains ? There's no upstream for the `iomklc` sub toolchains (i.e. `iompi`, or `iimkl`, or `iomkl`), nor for `gmkl`, `gomklc`, nor any of the toolchains based on PGI. 

We can adopt the upstream version for `gompic`, but that leaves MKL as a free variable. And we can adopt `iccifortcuda`, but that leaves out the OpenMPI version as a free variable. 

Is the suggestion to pick whatever OpenMPI version is used in the upstream `gompi` version, and apply it to Intel, and vice-versa for MKL, and then to try to push this upstream ?  i.e. are we trying to define the upstream standard for the combinations Intel + OpenMPI and GCC + MKL ?

**Comment by bartoldeman** [comment]
Yes upstream has no issues accepting any-toolchain-2020a as long as it's a mix or subset of components that are in foss and intel. That is, there is only one possibility to sanely define iompi/iimkl/iomkl/gmkl.

Now for the question marks in one of the comments:
Intel MPI 2019.7.217 (???) -- this is just Intel being strange, 2020 update 1 ships with this Intel MPI.
Intel MKL 2020.1.217 (???) (in iimkl-2020a) -- this is correct
Intel MKL 2020.0.166 (???) (in gmkl-2020a) -- this I forgot to update

as for CUDA, I think upstream will adopt CUDA 11.0 for 2020a.

For PGI, indeed it's not defined, so any upstream toolchain follows the year-month scheme as explained in the link (though we can keep using the 19.4.101 scheme we use for pgicuda).

**Comment by mboisson** [comment]
Ok. I think you have me convinced. 

So, we would have: 

A) in the simple case we would have version
- iccifort,2020.1.217   (should it be shorter ?) 
- GCC,9.3.0
For `2020a` : 
- iccifortcuda, iompi, iimkl, iompic, iomkl, iimklc, iomklc => combinations of {Intel compiler 2020.1.217, OpenMPI 4.0.3, MKL 2020.1.217, CUDA 11.0}
- gcccuda, gompi, gmkl, gompic, gomkl, gmklc, gomklc => combinations of {GCC 9.3.0 2020.1.217, OpenMPI 4.0.3, MKL 2020.1.217, CUDA 11.0}

B) If one of the component (other than the compiler) diverges, we use
- 2020a.{mpi_ver}.{cuda_ver}
(we don't let MKL diverge) 

C) For new compiler versions, we try to map to a future upstream toolchain version

D) For older compilers, we revert to using our previous schema, i.e. Intel 2018.3 / GCC 7.3.0, Intel 2016.4 / GCC 5.4.0, with {compiler_ver}.{mpi_ver}.{cuda_ver}


How many dots do we keep when collapsing versions for {mpi_ver} and {cuda_ver} ? 

@ccoulombe, any further comment ? @alikerr too, since you installed a lot of packages.

**Comment by ostueker** [comment]
> How many dots do we keep when collapsing versions for {mpi_ver} and {cuda_ver} ?

IMHO we should stick with the same contractions that we have been using since late 2017:
MPI 4.0.3 -> 403, etc.

**Comment by bartoldeman** [comment]
yes I'm happy with the 4.0.3 -> .403 scheme too. The collapsing in the modulepath (one- or two-digit rule) has to do with ABI compatibility, whereas in this case we don't upgrade toolchain components but keep the toolchain the same.

**Comment by mboisson** [comment]
What's the rationale to have different "collapsing" for the toolchain version than for the path ? That's what I'm wondering. Why have `403` in the version, but `4` in the path (or is it `40`) ?

**Comment by bartoldeman** [comment]
The difference is that e.g. if within a hypothetical iomkl 2018.3.31 you want to upgrade OpenMPI from 3.1.2 to 3.1.6, you would modify or regenerate the iomkl/.2018.3.31 in-place.

With the modulepath-only it means that applications that you compile with iomkl 2018.3.312 and iomkl 2018.3.316 go into the same directory tree and can link to each other (which is ok because of ABI-compatibility) but there is no in-place overwrite.

**Comment by mboisson** [comment]
With RPATH, you will still have applications that link to 3.1.2 in any case. But ok, in-place replacement (of OpenMPI in particular) is a good argument to keep full digits for the toolchain components themselves.

**Comment by ccoulombe** [comment]
What if we need a divergent MKL version?

Generally, I always prefer a more verbose scheme but ok since it is "easier" to identifie a default toolchain and contribute back. It will be confusing to use the old and newer toolchains but as long as we document it clearly (e.g. R 4.1 using GCC 7.3.0 + MKL and 2020a)

**Comment by mboisson** [comment]
GCC 7.3.0 would not be 2020a, it would be part of the older convention.

**Comment by mboisson** [comment]
Closing. Opened issue https://github.com/ComputeCanada/software-stack/issues/12 on documenting toolchains.
