### ISSUE TITLE
broken C.utf8 locale

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#81]
Encountered when trying to install SageMath

```
$ locale -a
C
C.utf8
en_CA.utf8
en_GB.utf8
en_US.utf8
fr_CA.utf8
POSIX
$ LC_ALL=C.utf8
-bash: warning: setlocale: LC_ALL: cannot change locale (C.utf8): No such file or directory
``` 
The other locales work fine.

**Comment by bartoldeman** [comment]
This actually seems to be an issue with CentOS bash:
```
[oldeman@build-node ~]$ module --force purge
[oldeman@build-node ~]$ LC_ALL=C.utf8
-bash: warning: setlocale: LC_ALL: cannot change locale (C.utf8): No such file or directory
[oldeman@build-node ~]$ which bash
/usr/bin/bash
[oldeman@build-node ~]$ bash
[oldeman@build-node ~]$ LC_ALL=C.utf8
bash: warning: setlocale: LC_ALL: cannot change locale (C.utf8): No such file or directory
[oldeman@build-node ~]$ exit
[oldeman@build-node ~]$ module load gentoo
[oldeman@build-node ~]$ bash
[oldeman@build-node ~]$ LC_ALL=C.utf8
[oldeman@build-node ~]$
```

**Comment by bartoldeman** [comment]
digging a bit more, this is a customization that many distributions do towards glibc, see here https://bugs.gentoo.org/671024 for Gentoo, and there is no need to put it in `locale.gen` since it's generated by default (see output of `locale -a`).

RHEL/CentOS7 doesn't support it but 8 does.

so the workaround is to run Gentoo `bash` instead of `/bin/bash`.

I'll close this then since there is nothing I can do to fix this.
