### ISSUE TITLE
Putting CUDA on top of OpenMPI, rather than below

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#97]
That would allow reusing gompi recipes with gompic. 

Would be nice to have for OpenMPI 4.1.1. 

The idea is to have `gompic` depend on `gompi` + `CUDA` + `UCX-CUDA` (or other variants for non-UCX systems).

**Comment by mboisson** [comment]
So, from chat on EasyBuild slack, I think that would work this way: 

- [ ] compile UCX with `gcccore` to dynamically load plugins (for CUDA)
- [ ] compile UCX-CUDA with `gcccorecuda`, and depend on UCX
- [ ] make each CUDA module depend on UCX-CUDA

That would automagically make OpenMPI aware of CUDA when a user loads a CUDA module. Thoughts @bartoldeman ?

**Comment by bartoldeman** [comment]
The `gompic/2020a` module now depends on `gcc`, `cuda` and `openmpi`. They each expand `$MODULEPATH` in turn:
```
gcc: .../avx2/Compiler/gcc9
cudacore: .../CUDA/cuda11.0 and avx2/CUDA/cuda11.0
cuda: .../avx2/CUDA/gcc9/cuda11.0
openmpi: .../avx2/MPI/gcc9/cuda11.0/openmpi4
```
the question is now where to get `.../avx2/MPI/gcc9/cuda11.0/openmpi4` from. `UCX-CUDA` can't do that since it doesn't know which OpenMPI to use yet.
One could also keep the CUDA-OpenMPI module, but modify it to use expand also MPI-without-CUDA, load UCX-CUDA, and use the same root as OpenMPI-without-CUDA. Though that's a little complex, since `modaltroot` can't be used directly, unless we use OpenMPIcore or some such ...

There's also opa-psm2 and libfabric for OmniPath networks, it goes beyond UCX. Though opa-psm2 only uses  `libcuda.so.1` via `dlopen` so it could be CUDA-version-agnostic, if smart enough (it broke things before, using CUDA-enabled opa-psm2 on CPU-only nodes, though perhaps that's been fixed).

So need to think about this some more.

**Comment by mboisson** [comment]
Maybe we can have: 
Compiler + CUDA => expand `CUDA/compilerV/cudaV` 
Compiler + MPI + CUDA (same module name, different layer) => expand both `CUDA/compilerV/cudaV` and `MPI/compilerV/mpiV/cudaV`

**Comment by bartoldeman** [comment]
yes that may work. Then cuda-at-MPI is installed using the gompi toolchain with a dependency on UCX-CUDA.
Remains to be seen how to deal with libfabric, though it provides FI_PROVIDER_PATH so it should be doable.

**Comment by mboisson** [comment]
Based on EasyBuild's upstream attempt, this can't be achieved for reasons explained in
https://github.com/open-mpi/ompi/issues/9906
